### ISSUE TITLE
command 'micropico.initialise' not found when configuring project

### ISSUE THREAD

**Issue by jsneer23** [paulober/MicroPico#247]
## What are the steps to reproduce this issue?

1. fresh install MicroPico v4.0.0 from extensions menu in vs code
2. `ctrl+shift+P` MicroPico: Configure MicroPico Project

## What happens?

a dialogue box appears that reads the following:

```
Command 'MicroPico: Configure MicroPico Project' resulted in an error

command 'micropico.initialise' not found
```

## What were you expecting to happen?

i was expecting MicroPico to initialize like it does in v3.8. if i downgrade to v3.8.4 things work.

## Any logs, error output, etc?

```
2024-09-11 00:47:52.477 [info] ExtensionService#_doActivateExtension paulober.pico-w-go, startup: false, activationEvent: 'onFileSystem:pico'
2024-09-11 00:47:52.551 [error] Activating extension paulober.pico-w-go failed due to an error:
2024-09-11 00:47:52.551 [error] Error: No native build was found for platform=linux arch=arm runtime=electron abi=123 uv=1 armv=default libc=glibc node=20.14.0 electron=30.1.2
    loaded from: /home/my_name/.vscode/extensions/paulober.pico-w-go-4.0.0-linux-armhf

	at g.resolve.g.path (/home/my_name/.vscode/extensions/paulober.pico-w-go-4.0.0-linux-armhf/dist/extension.cjs:1:16083)
	at g (/home/my_name/.vscode/extensions/paulober.pico-w-go-4.0.0-linux-armhf/dist/extension.cjs:1:14135)
	at Object.<anonymous> (/home/my_name/.vscode/extensions/paulober.pico-w-go-4.0.0-linux-armhf/dist/extension.cjs:1:16801)
	at u._compile (/usr/share/code/resources/app/out/bootstrap-fork.js:2:1257)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at E._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:177:6051)
	at i._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:31787)
	at o._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:139:34334)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at Function.i [as __$__nodeRequire] (/usr/share/code/resources/app/out/bootstrap-fork.js:3:98)
	at m.xb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:32966)
	at async Promise.all (index 0)
```

## Which version of MicroPico are you using?

v4.0.0

## Support info

```
Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux arm 6.6.31+rpt-rpi-v8
```

**Comment by jsneer23** [comment]
thanks!!
